containers:
  - name: test
    image: gcr.io/stock-react/test
  #Set db env
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: root
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: 123456
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: stock

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stock-react/example', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/stock-react/example']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'test', '--image', 'gcr.io/stock-react/example', '--region', 'us-central1', '--platform', 'managed','--port','80','--allow-unauthenticated']


